def_names = c("[0] normal",
              "[1] GALK Deficiency (H44Y)",
              "[2] GALK Deficiency (R68C)",
              "[3] GALK Deficiency (A198V)",
              "[4] GALK Deficiency (G346S)",
              "[5] GALK Deficiency (G347S)",
              "[6] GALK Deficiency (G349S)",
              "[7] GALK Deficiency (E43A)",
              "[8] GALK Deficiency (E43G)",
              "[9] GALT Deficiency (R201C)",
              "[10] GALT Deficiency (E220K)",
              "[11] GALT Deficiency (R223S)",
              "[12] GALT Deficiency (I278N)",
              "[13] GALT Deficiency (L289F)",
              "[14] GALT Deficiency (E291V)",
              "[15] GALE Deficiency (N34S)",
              "[16] GALE Deficiency (G90E)",
              "[17] GALE Deficiency (V94M)",
              "[18] GALE Deficiency (D103G)",
              "[19] GALE Deficiency (L183P)",
              "[20] GALE Deficiency (K257R)",
              "[21] GALE Deficiency (L313M)",
              "[22] GALE Deficiency (G319E)",
              "[23] GALE Deficiency (R335H)")
df$deficiency <- factor(df$deficiency,
                        levels = seq(0,23),
                        labels = def_names)
head(df)